/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogo.tela;



public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbtn_sair = new javax.swing.JToggleButton();
        tbtn_criar = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        tbtn_sair.setText("Sair");
        tbtn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn_sairActionPerformed(evt);
            }
        });
        getContentPane().add(tbtn_sair);
        tbtn_sair.setBounds(850, 590, 151, 64);

        tbtn_criar.setText("Criar Personagem");
        tbtn_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn_criarActionPerformed(evt);
            }
        });
        getContentPane().add(tbtn_criar);
        tbtn_criar.setBounds(850, 480, 151, 64);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telas/Tela inicial.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(2, -3, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtn_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn_criarActionPerformed
        CriacaoDePersonagem criacao = new CriacaoDePersonagem();
        criacao.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_tbtn_criarActionPerformed

    private void tbtn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn_sairActionPerformed
        if (tbtn_sair.isSelected()) {
           System.exit(0); 
        }
    }//GEN-LAST:event_tbtn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton tbtn_criar;
    private javax.swing.JToggleButton tbtn_sair;
    // End of variables declaration//GEN-END:variables
}
